name: meetup_api_scraper
description: Scrapes data from the Meetup API description & converts to an openapi file.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: any
  http: any
  quiver: any

dev_dependencies:
  pedantic: any
  test: any
